# This is a TOML document for CBFT configuration

[[sealers]]
    host="192.168.0.1"
    port=12345
    address="0x11111111"
    publicKey="0x11111111"
[[sealers]]
    host="192.168.0.2"
    port=12346
    address="0x22222222"
    publicKey="0x22222222"